// design-system-reference/lifeos_app_react/MenuRow.jsx
// MenuRow + SubRow — sidebar list items

const MenuRow = ({ item, expanded, onToggle, onClick, collapsed }) => {
  const handleClick = () => {
    if (item.expandable && onToggle) onToggle();
    else onClick && onClick(item);
  };
  return (
    <div className={`menu-row ${item.active ? "active" : ""} ${collapsed ? "collapsed" : ""}`}
         onClick={handleClick}
         title={collapsed ? item.label : undefined}>
      <span className="lead">
        <Icon name={item.icon} size={16} />
        {item.status && <span className="lead-status"><StatusDot status={item.status} /></span>}
        {collapsed && item.badge && <Badge {...item.badge} />}
      </span>
      {!collapsed && (
        <>
          <span className="body">
            <span className="label">{item.label}</span>
            {item.meta && <span className="meta">{item.meta}</span>}
          </span>
          {item.badge && <span className="trail"><Badge {...item.badge} /></span>}
          {item.shortcut && <Kbd>{item.shortcut}</Kbd>}
          {item.expandable && (
            <Icon name="chevron-down" size={14}
                  className="chev"
                  style={{ transform: expanded ? "rotate(180deg)" : "rotate(0)", transition: "transform .25s" }} />
          )}
        </>
      )}
    </div>
  );
};

const SubRow = ({ item }) => (
  <div className="sub-row">
    {item.status && <StatusDot status={item.status} />}
    <span className="sub-body">
      <span className="sub-label">{item.label}</span>
      {item.meta && <span className="sub-meta">{item.meta}</span>}
    </span>
  </div>
);

Object.assign(window, { MenuRow, SubRow });

// src/components/MenuRow.vue
<script setup>
// LifeOS — MenuRow SFC
// Renders a section item inside the workspace panel.

import Icon from "./Icon.vue";
import Badge from "./Badge.vue";

defineProps({
  item: { type: Object, required: true },
  collapsed: { type: Boolean, default: false },
});

defineEmits(["click"]);
</script>

<template>
  <div :class="['menu-row', { active: item.active, collapsed }]"
       data-figma-component="Sidebar Companion/Menu row"
       :title="collapsed ? item.label : undefined"
       role="button"
       tabindex="0"
       @click="$emit('click', item)"
       @keydown.enter.prevent="$emit('click', item)"
       @keydown.space.prevent="$emit('click', item)">
    <span class="lead">
      <Icon :name="item.icon || 'circle'" :size="16" />
      <span v-if="item.status" class="lead-status">
        <Badge dot :tone="item.status === 'warn' ? 'warn' : 'ok'" />
      </span>
      <Badge v-if="collapsed && item.badge" v-bind="item.badge" />
    </span>
    <template v-if="!collapsed">
      <span class="body">
        <span class="label">{{ item.label }}</span>
        <span v-if="item.meta" class="meta">{{ item.meta }}</span>
      </span>
      <span v-if="item.badge" class="trail"><Badge v-bind="item.badge" /></span>
      <kbd v-if="item.shortcut" class="kbd">{{ item.shortcut }}</kbd>
    </template>
  </div>
</template>
