// src/components/MenuRow.svelte
<script>
  // LifeOS — MenuRow SFC (Svelte port of MenuRow.vue)
  // Renders a section item inside the workspace panel.
  import Icon from "./Icon.svelte";
  import Badge from "./Badge.svelte";

  let { item, collapsed = false, onclick } = $props();

  function activate() {
    onclick?.(item);
  }

  function onRowKeydown(e) {
    if (e.key === "Enter" || e.key === " ") {
      e.preventDefault();
      activate();
    }
  }
</script>

<div class="menu-row" class:active={item.active} class:collapsed
     data-figma-component="Sidebar Companion/Menu row"
     title={collapsed ? item.label : undefined}
     role="button"
     tabindex="0"
     onclick={activate}
     onkeydown={onRowKeydown}>
  <span class="lead">
    <Icon name={item.icon || "circle"} size={16} />
    {#if item.status}
      <span class="lead-status">
        <Badge dot tone={item.status === "warn" ? "warn" : "ok"} />
      </span>
    {/if}
    {#if collapsed && item.badge}
      <Badge {...item.badge} />
    {/if}
  </span>
  {#if !collapsed}
    <span class="body">
      <span class="label">{item.label}</span>
      {#if item.meta}<span class="meta">{item.meta}</span>{/if}
    </span>
    {#if item.badge}<span class="trail"><Badge {...item.badge} /></span>{/if}
    {#if item.shortcut}<kbd class="kbd">{item.shortcut}</kbd>{/if}
  {/if}
</div>

// src/components/MenuRow.vue
<script setup>
// LifeOS — MenuRow SFC
// Renders a section item inside the workspace panel.

import Icon from "./Icon.vue";
import Badge from "./Badge.vue";

defineProps({
  item: { type: Object, required: true },
  collapsed: { type: Boolean, default: false },
});

defineEmits(["click"]);
</script>

<template>
  <div :class="['menu-row', { active: item.active, collapsed }]"
       data-figma-component="Sidebar Companion/Menu row"
       :title="collapsed ? item.label : undefined"
       role="button"
       tabindex="0"
       @click="$emit('click', item)"
       @keydown.enter.prevent="$emit('click', item)"
       @keydown.space.prevent="$emit('click', item)">
    <span class="lead">
      <Icon :name="item.icon || 'circle'" :size="16" />
      <span v-if="item.status" class="lead-status">
        <Badge dot :tone="item.status === 'warn' ? 'warn' : 'ok'" />
      </span>
      <Badge v-if="collapsed && item.badge" v-bind="item.badge" />
    </span>
    <template v-if="!collapsed">
      <span class="body">
        <span class="label">{{ item.label }}</span>
        <span v-if="item.meta" class="meta">{{ item.meta }}</span>
      </span>
      <span v-if="item.badge" class="trail"><Badge v-bind="item.badge" /></span>
      <kbd v-if="item.shortcut" class="kbd">{{ item.shortcut }}</kbd>
    </template>
  </div>
</template>
