// src/components/Dashboard.vue
<script setup>
// LifeOS — Dashboard SFC
// Main canvas: greeting + 4 stat cards + agent-team grid (drag+click) + activity + agenda + AI suggest.

import { ref, computed } from "vue";
import { useLifeos } from "@/stores/lifeos.js";
import { useToasts } from "@/stores/toasts.js";
import { useNav } from "@/lib/nav.js";
import Icon from "./Icon.vue";
import TelemetryWidget from "./TelemetryWidget.vue";

const lifeos = useLifeos();
const toasts = useToasts();
const nav = useNav();
const d = (window).LIFEOS_DATA?.dashboardCanvas;
const TONE = (window).TONE || {};
const teams = computed(() => lifeos.teams);
const aiAgentTeamItems = computed(() =>
  (window).LIFEOS_DATA?.workspaces?.ai?.sections?.find((s) => s.title === "Agent Teams")?.items || []);

// drag-reorder
const dragId = ref(null);
const overId = ref(null);
const onDragStart = (e, id) => {
  dragId.value = id;
  e.dataTransfer.effectAllowed = "move";
  e.dataTransfer.setData("text/plain", id);
};
const onDragOver = (e) => { e.preventDefault(); e.dataTransfer.dropEffect = "move"; };
const onDrop = (e, targetId) => {
  e.preventDefault();
  const sourceId = dragId.value;
  dragId.value = null; overId.value = null;
  if (!sourceId || sourceId === targetId) return;
  const current = teams.value.map((t) => t.id);
  const fromIdx = current.indexOf(sourceId);
  const toIdx = current.indexOf(targetId);
  if (fromIdx < 0 || toIdx < 0) return;
  const next = [...current];
  const [m] = next.splice(fromIdx, 1);
  next.splice(toIdx, 0, m);
  lifeos.setTeamOrder(next);
};

// click → flow
const openTeam = (t) => {
  const idx = aiAgentTeamItems.value.findIndex(x => x.flowId === t.flowId);
  const enriched = idx >= 0
    ? Object.assign({}, aiAgentTeamItems.value[idx], { _teamIndex: idx })
    : { label: t.name, icon: t.icon, view: "n8n-flow", flowId: t.flowId, _teamIndex: 0 };
  nav.jumpToTeam(enriched, idx >= 0 ? idx : 0);
};

const toneOf = (key) => TONE[key] || { bg: "transparent", fg: "var(--fg-0)", bd: "var(--bg-5)" };

// Dashboard CTAs (Phase 4 #3) — wire to real behaviors where they exist;
// surface "coming soon" for shells we haven't built yet (Activity feed, Agenda sync, suggestion-apply).
const askLifeOS = () => lifeos.toggleAiChat();
const newAutomation = () => {
  // Open the command palette pre-seeded so the user can pick an existing workflow
  // to clone, or land in the AI chat with the /new-automation slash command.
  lifeos.openCmdk("automation");
};
const comingSoon = (label) => {
  toasts.info(`${label} is coming soon.`);
};
</script>

<template>
  <div v-if="!d" class="canvas"><h1 class="canvas-greeting">Loading…</h1></div>
  <div v-else class="canvas">
    <header class="canvas-head">
      <div>
        <div class="canvas-eyebrow">Tuesday · 19 May</div>
        <h1 class="canvas-greeting">{{ d.greeting }}</h1>
        <p class="canvas-sub">{{ d.sub }}</p>
      </div>
      <div class="canvas-actions">
        <button class="btn-gradient" aria-label="Ask LifeOS" @click="askLifeOS"><Icon name="sparkles" :size="14" />Ask LifeOS</button>
        <button class="btn-secondary" aria-label="New automation" @click="newAutomation"><Icon name="plus" :size="14" />New automation</button>
      </div>
    </header>

    <div class="stats-grid" role="group" aria-label="Workspace overview">
      <div v-for="(s, i) in d.stats" :key="s.id" class="fade-in-up" :style="{ animationDelay: i * 50 + 'ms' }">
        <div class="stat-card"
             role="img"
             :aria-label="`${s.label}: ${s.value}${s.unit || ''}, ${s.delta}`"
             :style="{
               background: `linear-gradient(180deg, ${toneOf(s.tone).bg} 0%, transparent 60%), var(--bg-2)`,
               borderColor: toneOf(s.tone).bd,
             }">
          <div class="stat-head">
            <span class="stat-ico" :style="{ background: toneOf(s.tone).bg, color: toneOf(s.tone).fg }">
              <Icon :name="s.icon" :size="16" />
            </span>
            <span class="stat-delta" :style="{ color: toneOf(s.tone).fg }">{{ s.delta }}</span>
          </div>
          <div class="stat-value">{{ s.value }}<span class="stat-unit">{{ s.unit }}</span></div>
          <div class="stat-label">{{ s.label }}</div>
          <div class="stat-meta">{{ s.meta }}</div>
        </div>
      </div>
    </div>

    <TelemetryWidget />

    <div class="teams-block">
      <div class="teams-head">
        <h2>Your agent teams</h2>
        <span class="teams-meta">{{ teams.length }} teams · 21 agents · running now</span>
        <span class="teams-hint"><Icon name="move" :size="11" /> drag to reorder · click to open</span>
      </div>
      <div class="teams-grid">
        <button v-for="(t, i) in teams" :key="t.id"
                :class="['team-card', { 'is-dragging': dragId === t.id, 'is-drop-target': overId === t.id && dragId !== t.id }]"
                :style="{ borderColor: toneOf(t.tone).bd, animationDelay: i * 60 + 'ms' }"
                draggable="true"
                :aria-label="`Open ${t.name} workflow`"
                @click="openTeam(t)"
                @dragstart="onDragStart($event, t.id)"
                @dragover="onDragOver"
                @dragenter="overId = t.id"
                @dragleave="overId === t.id && (overId = null)"
                @drop="onDrop($event, t.id)"
                @dragend="dragId = null; overId = null">
          <div class="team-head">
            <span class="team-ico" :style="{ background: toneOf(t.tone).bg, color: toneOf(t.tone).fg }">
              <Icon :name="t.icon" :size="14" />
            </span>
            <span class="team-name">{{ t.name }}</span>
            <span class="team-status">
              <span class="team-dot"
                    :style="{
                      background: t.status === 'warn' ? 'var(--status-warn)' : 'var(--lifeos-green)',
                      boxShadow: t.status === 'online' ? `0 0 8px ${t.status === 'warn' ? 'var(--status-warn)' : 'var(--lifeos-green)'}` : 'none'
                    }" />
            </span>
            <span class="team-grip" aria-hidden="true"><Icon name="grip-vertical" :size="12" /></span>
          </div>
          <div class="team-meta">{{ t.meta }}</div>
          <div class="team-foot">
            <span class="team-counter" :style="{ color: toneOf(t.tone).fg }">{{ t.counter }}</span>
            <span class="team-cta">Open <Icon name="arrow-right" :size="11" /></span>
          </div>
        </button>
      </div>
    </div>

    <div class="canvas-cols">
      <div class="col-card">
        <div class="col-head"><h3>Activity feed</h3><button class="link-btn" @click="comingSoon('View all activity')">View all</button></div>
        <ul class="activity-list">
          <li v-for="(a, i) in d.activity" :key="i" class="activity-row">
            <span class="activity-ico" :style="{ background: toneOf(a.tone).bg, color: toneOf(a.tone).fg }">
              <Icon :name="a.icon" :size="14" />
            </span>
            <span class="activity-body">
              <span class="activity-title">{{ a.title }}</span>
              <span class="activity-meta">{{ a.meta }}</span>
            </span>
            <span class="activity-time">{{ a.time }}</span>
          </li>
        </ul>
      </div>
      <div class="col-card">
        <div class="col-head"><h3>Today's agenda</h3><button class="link-btn" @click="comingSoon('Sync agenda')">Sync</button></div>
        <ul class="agenda-list">
          <li v-for="(a, i) in d.agenda" :key="i" class="agenda-row">
            <span class="agenda-time">{{ a.time }}</span>
            <span class="agenda-bar" :style="{ background: toneOf(a.tone).fg }" />
            <span class="agenda-body">
              <span class="agenda-title">{{ a.title }}</span>
              <span class="agenda-tag" :style="{ background: toneOf(a.tone).bg, color: toneOf(a.tone).fg, border: `1px solid ${toneOf(a.tone).bd}` }">{{ a.tag }}</span>
            </span>
          </li>
        </ul>
        <div class="ai-suggest" role="status" aria-live="polite">
          <span class="ai-ico" aria-hidden="true"><Icon name="sparkles" :size="14" /></span>
          <div><strong>LifeOS suggests:</strong> move standup to 2:30 to clear a 60-min focus block.</div>
          <button class="link-btn cyan" @click="comingSoon('Apply LifeOS suggestion')">Apply</button>
        </div>
      </div>
    </div>
  </div>
</template>

// design-system-reference/lifeos_app_react/Dashboard.jsx
// Dashboard — main canvas. Renders for every workspace.
// Includes clickable + draggable agent team cards.

const StatCard = ({ s }) => {
  const t = (window.TONE && window.TONE[s.tone]) || (window.TONE && window.TONE.cyan) || { bg: "transparent", fg: "#fff", bd: "#333" };
  return (
    <div className="stat-card" style={{
      background: `linear-gradient(180deg, ${t.bg} 0%, transparent 60%), var(--bg-2)`,
      borderColor: t.bd,
    }}>
      <div className="stat-head">
        <span className="stat-ico" style={{ background: t.bg, color: t.fg }}>
          <Icon name={s.icon} size={16} />
        </span>
        <span className="stat-delta" style={{ color: t.fg }}>{s.delta}</span>
      </div>
      <div className="stat-value">
        {s.value}<span className="stat-unit">{s.unit}</span>
      </div>
      <div className="stat-label">{s.label}</div>
      <div className="stat-meta">{s.meta}</div>
    </div>
  );
};

const ActivityItem = ({ a }) => {
  const t = (window.TONE && window.TONE[a.tone]) || (window.TONE && window.TONE.info) || { bg: "transparent", fg: "#fff" };
  return (
    <li className="activity-row">
      <span className="activity-ico" style={{ background: t.bg, color: t.fg }}>
        <Icon name={a.icon} size={14} />
      </span>
      <span className="activity-body">
        <span className="activity-title">{a.title}</span>
        <span className="activity-meta">{a.meta}</span>
      </span>
      <span className="activity-time">{a.time}</span>
    </li>
  );
};

const AgendaItem = ({ a }) => {
  const t = (window.TONE && window.TONE[a.tone]) || (window.TONE && window.TONE.cyan) || { bg: "transparent", fg: "#fff", bd: "#333" };
  return (
    <li className="agenda-row">
      <span className="agenda-time">{a.time}</span>
      <span className="agenda-bar" style={{ background: t.fg }} />
      <span className="agenda-body">
        <span className="agenda-title">{a.title}</span>
        <span className="agenda-tag" style={{ background: t.bg, color: t.fg, border: `1px solid ${t.bd}` }}>{a.tag}</span>
      </span>
    </li>
  );
};

// Map dashboard team id → AI workspace expansion key
const TEAM_NAME_BY_ID = {
  "day":      "Day Captain",
  "inbox":    "Inbox Crew",
  "research": "Research Squad",
  "home-ops": "Home Ops",
  "wellness": "Wellness Crew",
  "finance":  "Finance Bench",
};

const AgentTeamCard = ({ t, idx, dragState, onClick, onDragStart, onDragOver, onDragEnter, onDragLeave, onDrop, onDragEnd }) => {
  const tone = (window.TONE && window.TONE[t.tone]) || (window.TONE && window.TONE.cyan) || { bg: "transparent", fg: "#fff", bd: "#333" };
  const statusColor = t.status === "warn" ? "var(--status-warn)" : "var(--lifeos-green)";
  const isDragging = dragState?.draggingId === t.id;
  const isDropTarget = dragState?.overId === t.id && dragState?.draggingId !== t.id;
  return (
    <button
      type="button"
      className={`team-card ${isDragging ? "is-dragging" : ""} ${isDropTarget ? "is-drop-target" : ""}`}
      style={{ borderColor: tone.bd, animationDelay: `${idx * 60}ms` }}
      draggable
      onClick={onClick}
      onDragStart={onDragStart}
      onDragOver={onDragOver}
      onDragEnter={onDragEnter}
      onDragLeave={onDragLeave}
      onDrop={onDrop}
      onDragEnd={onDragEnd}
      aria-label={`Open ${t.name} in AI Command Center`}
    >
      <div className="team-head">
        <span className="team-ico" style={{ background: tone.bg, color: tone.fg }}>
          <Icon name={t.icon} size={14} />
        </span>
        <span className="team-name">{t.name}</span>
        <span className="team-status">
          <span className="team-dot" style={{ background: statusColor, boxShadow: t.status === "online" ? `0 0 8px ${statusColor}` : "none" }} />
        </span>
        <span className="team-grip" aria-hidden="true">
          <Icon name="grip-vertical" size={12} />
        </span>
      </div>
      <div className="team-meta">{t.meta}</div>
      <div className="team-foot">
        <span className="team-counter" style={{ color: tone.fg }}>{t.counter}</span>
        <span className="team-cta">Open <Icon name="arrow-right" size={11} /></span>
      </div>
    </button>
  );
};

const Dashboard = ({ onSelectWorkspace, onJumpToTeam }) => {
  const d = window.LIFEOS_DATA?.dashboardCanvas;
  const [teams, setTeams] = useState(() => d?.teams || []);
  const [dragState, setDragState] = useState({ draggingId: null, overId: null });

  if (!d) {
    return <div className="canvas"><h1 className="canvas-greeting">Loading…</h1></div>;
  }

  // Resolve the AI workspace's "Agent Teams" section position once
  const aiWs = window.LIFEOS_DATA.workspaces.ai;
  const agentTeamsItems = aiWs?.sections?.find(s => s.title === "Agent Teams")?.items || [];

  const handleClick = (t) => {
    const idx = agentTeamsItems.findIndex(x => x.flowId === t.flowId);
    const enriched = idx >= 0
      ? { ...agentTeamsItems[idx], _teamIndex: idx }
      : { label: t.name, icon: t.icon, view: "n8n-flow", flowId: t.flowId, _teamIndex: 0 };
    onJumpToTeam?.(enriched);
  };

  const handleDragStart = (e, id) => {
    setDragState({ draggingId: id, overId: null });
    e.dataTransfer.effectAllowed = "move";
    e.dataTransfer.setData("text/plain", id);
  };
  const handleDragOver = (e) => { e.preventDefault(); e.dataTransfer.dropEffect = "move"; };
  const handleDragEnter = (id) => setDragState(s => ({ ...s, overId: id }));
  const handleDragLeave = (id) => setDragState(s => s.overId === id ? { ...s, overId: null } : s);
  const handleDrop = (e, targetId) => {
    e.preventDefault();
    const sourceId = dragState.draggingId;
    if (!sourceId || sourceId === targetId) { setDragState({ draggingId: null, overId: null }); return; }
    setTeams(prev => {
      const next = [...prev];
      const fromIdx = next.findIndex(x => x.id === sourceId);
      const toIdx = next.findIndex(x => x.id === targetId);
      if (fromIdx < 0 || toIdx < 0) return prev;
      const [moved] = next.splice(fromIdx, 1);
      next.splice(toIdx, 0, moved);
      return next;
    });
    setDragState({ draggingId: null, overId: null });
  };
  const handleDragEnd = () => setDragState({ draggingId: null, overId: null });

  return (
    <div className="canvas">
      <header className="canvas-head">
        <div>
          <div className="canvas-eyebrow">Tuesday · 19 May</div>
          <h1 className="canvas-greeting">{d.greeting}</h1>
          <p className="canvas-sub">{d.sub}</p>
        </div>
        <div className="canvas-actions">
          <button className="btn-gradient"><Icon name="sparkles" size={14} />Ask LifeOS</button>
          <button className="btn-secondary"><Icon name="plus" size={14} />New automation</button>
        </div>
      </header>

      <div className="stats-grid">
        {d.stats.map((s, i) => (
          <div key={s.id} className="fade-in-up" style={{ animationDelay: `${i * 50}ms` }}>
            <StatCard s={s} />
          </div>
        ))}
      </div>

      <div className="teams-block">
        <div className="teams-head">
          <h3>Your agent teams</h3>
          <span className="teams-meta">{teams.length} teams · 21 agents · running now</span>
          <span className="teams-hint"><Icon name="move" size={11} /> drag to reorder · click to open</span>
        </div>
        <div className="teams-grid">
          {teams.map((t, i) => (
            <AgentTeamCard key={t.id} t={t} idx={i}
              dragState={dragState}
              onClick={() => handleClick(t)}
              onDragStart={(e) => handleDragStart(e, t.id)}
              onDragOver={handleDragOver}
              onDragEnter={() => handleDragEnter(t.id)}
              onDragLeave={() => handleDragLeave(t.id)}
              onDrop={(e) => handleDrop(e, t.id)}
              onDragEnd={handleDragEnd}
            />
          ))}
        </div>
      </div>

      <div className="canvas-cols">
        <div className="col-card">
          <div className="col-head">
            <h3>Activity feed</h3>
            <button className="link-btn">View all</button>
          </div>
          <ul className="activity-list">
            {d.activity.map((a, i) => <ActivityItem a={a} key={i} />)}
          </ul>
        </div>

        <div className="col-card">
          <div className="col-head">
            <h3>Today's agenda</h3>
            <button className="link-btn">Sync</button>
          </div>
          <ul className="agenda-list">
            {d.agenda.map((a, i) => <AgendaItem a={a} key={i} />)}
          </ul>
          <div className="ai-suggest">
            <span className="ai-ico"><Icon name="sparkles" size={14} /></span>
            <div>
              <strong>LifeOS suggests:</strong> move standup to 2:30 to clear a 60-min focus block.
            </div>
            <button className="link-btn cyan">Apply</button>
          </div>
        </div>
      </div>
    </div>
  );
};

Object.assign(window, { Dashboard, AgentTeamCard, StatCard, ActivityItem, AgendaItem });
