// src/App.vue
<script setup>
// LifeOS — App SFC (root shell)
// The auth gate is the only top-level branch: Login covers the viewport until
// the auth store reports `signed_in`. loadStatus() runs once on mount so the
// gate reflects the backend (no account → signup; account but no session →
// welcome-back signin).

import { onMounted } from "vue";
import { useLifeos } from "@/stores/lifeos.js";
import { useAuth } from "@/stores/auth";
import Sidebar from "./components/Sidebar.vue";
import Workspace from "./components/Workspace.vue";
import Dashboard from "./components/Dashboard.vue";
import SubsectionView from "./components/SubsectionView.vue";
import N8nFlowView from "./components/N8nFlowView.vue";
import OpenPencilEditor from "./components/OpenPencilEditor.vue";
import LightsView from "./components/LightsView.vue";
import CalendarView from "./components/CalendarView.vue";
import FilesView from "./components/FilesView.vue";
import HealthView from "./components/HealthView.vue";
import IoTView from "./components/IoTView.vue";
import ContactsView from "./components/ContactsView.vue";
import SettingsView from "./components/SettingsView.vue";
import AIAvatar from "./components/AIAvatar.vue";
import CommandPalette from "./components/CommandPalette.vue";
import KeyboardHelp from "./components/KeyboardHelp.vue";
import ToastContainer from "./components/ToastContainer.vue";
import NotificationsDrawer from "./components/NotificationsDrawer.vue";
import Login from "./views/Login.vue";

const lifeos = useLifeos();
const auth = useAuth();

onMounted(() => {
  auth.loadStatus();
});
</script>

<template>
  <Login v-if="!auth.isSignedIn" />
  <div v-else :class="['shell', { 'ws-collapsed': lifeos.wsCollapsed }]">
    <Sidebar />
    <Workspace />
    <main class="main" id="main" tabindex="-1">
      <SettingsView       v-if="lifeos.activeId === 'settings' && !lifeos.activeSub" />
      <ContactsView       v-else-if="lifeos.activeId === 'contacts' && !lifeos.activeSub" />
      <Dashboard          v-else-if="!lifeos.activeSub" />
      <OpenPencilEditor   v-else-if="lifeos.activeSub.item?.view === 'open-pencil'" :sub="lifeos.activeSub" />
      <N8nFlowView        v-else-if="lifeos.activeSub.item?.view === 'n8n-flow'" />
      <LightsView         v-else-if="lifeos.activeSub.item?.view === 'lights'" />
      <CalendarView       v-else-if="lifeos.activeSub.item?.view === 'calendar'" />
      <FilesView          v-else-if="lifeos.activeSub.item?.view === 'files'" />
      <HealthView         v-else-if="lifeos.activeSub.item?.view === 'health'" />
      <IoTView            v-else-if="lifeos.activeSub.item?.view === 'iot'" />
      <ContactsView       v-else-if="lifeos.activeSub.item?.view === 'contacts'" />
      <SubsectionView     v-else />
    </main>
    <AIAvatar />
    <CommandPalette />
    <KeyboardHelp />
    <NotificationsDrawer />
    <ToastContainer />
  </div>
</template>

// src/App.svelte
<script>
  // LifeOS — App SFC (root shell), Svelte port of App.vue — phases 1+2 of the
  // blueprint-mandated Vue→Svelte migration (blueprint invariant 4: Tauri/Svelte
  // Glass). See [[tasks/blueprint-glass-svelte-migration]].
  //
  // Phase 2 replaced the phase-1 `data-view-pane` placeholders with the real
  // ported view panes and overlays — the <main> branch chain below now mirrors
  // App.vue 1:1 (same branch order, same discriminators, including the
  // OpenPencil mounting gate `activeSub.item?.view === 'open-pencil'`).
  //
  // This component is the mounted Glass root from src/main.ts. Navigation still
  // uses the shared router/store contract so the Svelte shell preserves the
  // existing route and persistence behavior while Vue artifacts are retired.
  //
  // The auth gate is the only top-level branch: Login covers the viewport until
  // the auth store reports `signed_in`. loadStatus() runs once on mount so the
  // gate reflects the backend (no account → signup; account but no session →
  // welcome-back signin).
  import { onMount } from "svelte";
  import { useLifeos } from "@/stores/lifeos.js";
  import { useAuth } from "@/stores/auth";
  import { bindStore } from "@/lib/pinia-bridge.svelte.js";
  import { router as appRouter } from "@/router";
  import Sidebar from "./components/Sidebar.svelte";
  import Workspace from "./components/Workspace.svelte";
  import Dashboard from "./components/Dashboard.svelte";
  import SubsectionView from "./components/SubsectionView.svelte";
  import N8nFlowView from "./components/N8nFlowView.svelte";
  import OpenPencilEditor from "./components/OpenPencilEditor.svelte";
  import EngineRoomTerminal from "./components/EngineRoomTerminal.svelte";
  import LightsView from "./components/LightsView.svelte";
  import CalendarView from "./components/CalendarView.svelte";
  import FilesView from "./components/FilesView.svelte";
  import HealthView from "./components/HealthView.svelte";
  import IoTView from "./components/IoTView.svelte";
  import ContactsView from "./components/ContactsView.svelte";
  import SettingsView from "./components/SettingsView.svelte";
  import AIAvatar from "./components/AIAvatar.svelte";
  import CommandPalette from "./components/CommandPalette.svelte";
  import KeyboardHelp from "./components/KeyboardHelp.svelte";
  import ToastContainer from "./components/ToastContainer.svelte";
  import NotificationsDrawer from "./components/NotificationsDrawer.svelte";
  import Login from "./views/Login.svelte";

  let { router = appRouter } = $props();

  const lifeos = useLifeos();
  const auth = useAuth();
  const authState = bindStore(auth, ["isSignedIn"]);
  const lifeosState = bindStore(lifeos, ["wsCollapsed", "activeId", "activeSub"]);

  onMount(() => {
    auth.loadStatus();
  });
</script>

{#if !authState.isSignedIn}
  <Login />
{:else}
  <div class="shell" class:ws-collapsed={lifeosState.wsCollapsed}>
    <Sidebar {router} />
    <Workspace {router} />
    <main class="main" id="main" tabindex="-1">
      {#if lifeosState.activeId === "settings" && !lifeosState.activeSub}
        <SettingsView />
      {:else if lifeosState.activeId === "contacts" && !lifeosState.activeSub}
        <ContactsView {router} />
      {:else if !lifeosState.activeSub}
        <Dashboard {router} />
      {:else if lifeosState.activeSub.item?.view === "open-pencil"}
        <OpenPencilEditor sub={lifeosState.activeSub} {router} />
      {:else if lifeosState.activeSub.item?.view === "terminal"}
        <EngineRoomTerminal />
      {:else if lifeosState.activeSub.item?.view === "n8n-flow"}
        <N8nFlowView />
      {:else if lifeosState.activeSub.item?.view === "lights"}
        <LightsView {router} />
      {:else if lifeosState.activeSub.item?.view === "calendar"}
        <CalendarView {router} />
      {:else if lifeosState.activeSub.item?.view === "files"}
        <FilesView {router} />
      {:else if lifeosState.activeSub.item?.view === "health"}
        <HealthView {router} />
      {:else if lifeosState.activeSub.item?.view === "iot"}
        <IoTView {router} />
      {:else if lifeosState.activeSub.item?.view === "contacts"}
        <ContactsView {router} />
      {:else}
        <SubsectionView />
      {/if}
    </main>
    <AIAvatar />
    <CommandPalette {router} />
    <KeyboardHelp />
    <NotificationsDrawer />
    <ToastContainer />
  </div>
{/if}
